## NUMPY

In [12]:
def func_python(N):
    d=0
    for i in range(N):
        d += (i % 3 - 1) * i
    return d

In [13]:
%timeit func_python(10000)

857 µs ± 11.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
distance = [45,50,35]
speed = [5,10,7]


time = distance/speed 
print (time)

TypeError: unsupported operand type(s) for /: 'list' and 'list'

**Introduction to NumPy**

NumPy (short form for Numerical Python) is the most fundamental package designed for scientific computing and data analysis. Most of the other packages such as pandas, statsmodels are built on top of it, and is an important package to know and learn about. At the heart of NumPy is a data structure called **ndarray**. ndarray is a basically a multi-dimensional array that is built specifically for the purpose of numerical data analysis. Python also has array capabilities, but they are more generic. <b>The advantage of using ndarray is that processing is extremely efficient and fast.</b> 

You can perform standard mathematical operations on either individual elements or complete array. The range of functions covered is <b>linear algebra, statistical operations, and other specialized mathematical operations</b>. For our purpose, we need to know about <b>ndarray and the range of mathematical functions that are relevant to our research purpose</b>. If you already know languages such as C, Fortran, then you can integrate NumPy code with code written in these languages and can pass NumPy arrays seamlessly. 

From an overall perspective, understanding of <b>NumPy will help us in using pandas effectively as it is built on top of NumPy and frequently we will also be using functions of NumPy in research work</b>. In the current session, we will only look at some of the most important features of NumPy. For a full listing of NumPy features, please visit http://wiki.scipy.org/Numpy_Example_List .

Possible application of NumPy package in research work are:
<i>
+ Algorithmic operations such as sorting, grouping and set operations
+ Performing repetitive operations on whole arrays of data without using loops
+ Data merging and alignment operations
+ Data indexing, filtering, and transformation on individual elements or whole arrays
+ Data summarization and descriptive statistics
</i>
**Installing NumPy**

In order to check if NumPy is installed, go to Package Manager and type NumPy. You will get a list of packages with names closely matching to NumPy. For our purpose, we need to focus on package named numpy 1.xx. If the package is not installed, click on Install. 

**Importing NumPy**

In order to be able to use NumPy, first import it using import statement

In [16]:
import numpy as np

The above statement will import all of NumPy into your workspace. For starters its good, but if you are doing performance intensive work, then saving space is of importance. In such cases, you can import specific modules of NumPy by using

In [17]:
# How we have overcome the prior challenge using 
dist = np.array(distance)
spd = np.array(speed)
print (dist)
print (spd)
time= dist/spd
print (time)
len(time)

[45 50 35]
[ 5 10  7]
[9. 5. 5.]


3

ndarray
The most important data structure in NumPy is an n-dimensional array object. Using ndarray, you can store large multidimensional datasets in Python. Being an array, you can <b>perform mathematical operations on these arrays either one element at a time or on complete arrays without using loops</b>. The way to initialize an array object is

In [19]:
a=[1,2,3,4,5]                                 # initialize a list and assign values to it
b=[10,20,30,40,50]
print (a + b)
#print (a + 5)                               #Want to add '5' to all the elements in the list
c = [val + 5 for val in a]           
print (c)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[6, 7, 8, 9, 10]


In [20]:
a = np.array((1,2,3,4,5))                       # initializes an array a and assigns values to it
b = np.array((10,20,30,40,50))                  # initializes another array b
#print (a)
#print (b)
print(a+b) 
print (a+5) 
a[2] = 15
b**3
a

[11 22 33 44 55]
[ 6  7  8  9 10]


array([ 1,  2, 15,  4,  5])

In [21]:
c = np.array(np.arange(10))                           #arange function here works as a sequence or counter in increments of 1
print ('array:     ', c)
print()
print()

anarray = np.array(np.arange(5,56,5))                 #arange function here works as a sequence or counter in increments of 5
print ('anarray:              ', anarray)
print()
print()

onemorearray = np.array(np.linspace(3,5,10))           #linspace function here creates 11 evenly spaced numbers over a specified interval
print ('onemorearray:         ', onemorearray)
print ('Rounded onemorearray: ', np.round(onemorearray,0))
onemorearray.sum()

array:      [0 1 2 3 4 5 6 7 8 9]


anarray:               [ 5 10 15 20 25 30 35 40 45 50 55]


onemorearray:          [3.         3.22222222 3.44444444 3.66666667 3.88888889 4.11111111
 4.33333333 4.55555556 4.77777778 5.        ]
Rounded onemorearray:  [3. 3. 3. 4. 4. 4. 4. 5. 5. 5.]


40.0

With each ndarray are associated two attributes: shape of the array, and type of the array. The <font color='red'><b>shape</b> of the array tells you about <b><u>dimensionality</u></b> of the array (rows and columns), and <b>type</b> of the array tells you about the <b><u>data type</u></b> contained</font> in the array.

In [22]:
data = np.array((32,45,123,756,23,2123,1,2,3,4,5,6,6,5,4,3,2,1,78,89,87,76,54,31))
data = data.reshape(8,3)
data2 = data.reshape(2,3,2,2)
print(data)
print ("*****")
print (data2)
print(data2.shape)
print(data2.dtype)
print(data2.size)
#even_data = (data % 2 == 0)
#data[even_data]

[[  32   45  123]
 [ 756   23 2123]
 [   1    2    3]
 [   4    5    6]
 [   6    5    4]
 [   3    2    1]
 [  78   89   87]
 [  76   54   31]]
*****
[[[[  32   45]
   [ 123  756]]

  [[  23 2123]
   [   1    2]]

  [[   3    4]
   [   5    6]]]


 [[[   6    5]
   [   4    3]]

  [[   2    1]
   [  78   89]]

  [[  87   76]
   [  54   31]]]]
(2, 3, 2, 2)
int32
24


In [23]:
np.zeros(50) + 5                        # Make a 50, 0 numbered single dimensional array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [24]:
np.zeros((3,5)) + 6                     # Make a 15, 0 numbered 2 dimensional array

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [25]:
np.ones(30) + 7                         # Make a 30, 1 numbered single dimensional array

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [26]:
np.ones((5,9))                       # Make a 45, 1 numbered 2 dimensional array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
np.eye(5)                            # creates a 5*5 identity matrix. 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.diag(np.array([1,3,5,3,4,5]))        # Populate the diagonal elements only

array([[1, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])